-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 616c1ebd1898c91de9a0548866a59cbd9f4547f6
    hooks:
    -   id: trailing-whitespace
        files: \.(md|py|txt|sh)$
    -   id: end-of-file-fixer
        files: \.(md|py|txt|sh)$
    -   id: debug-statements
        files: \.py$
    -   id: name-tests-test
        files: tests/.+\.py$
        exclude: tests/testing.*\.py$
    -   id: flake8
        files: \.py$
-   repo: local
    hooks:
    -   id: system
        name: PyLint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
