-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.3.0
    hooks:
    -   id: trailing-whitespace
        files: \.(md|py|txt|sh)$
    -   id: end-of-file-fixer
        files: \.(md|py|txt|sh)$
    -   id: debug-statements
        files: \.py$
    -   id: name-tests-test
        files: tests/.+\.py$
    -   id: flake8
        files: \.py$
