language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
#   - pypy
#   - pypy3
env:
    - TOXENV=lint
    - TOXENV=test
matrix:
    # notify a failed build as soon as anything fails
    fast_finish: true
    exclude:
        # pylint has dropped 2.6 support -.-
        - python: "2.6"
          env: TOXENV=lint
install: pip install -r requirements.d/travis.txt
script: tox
after_success:
    - find -name '.coverage*' | xargs mv -t .
    - coverage combine
    - coveralls
after_failure:
    # attempt to show any pip.log on failure
    - find -name pip.log | xargs -r tail -n99999


# public caches only supported under sudo:false currently
#   closest thing to documentation:
#   http://blog.travis-ci.com/2014-10-07-free-builds-for-students-github-student-developer-pack
sudo: false
cache:
    directories:
        - $HOME/.pip
        - $HOME/.pre-commit
